# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone
            storage:
                directory: "%kernel.root_dir%/../uploads/"
    chunks:
        maxage: 86400
        storage:
            directory: "%kernel.root_dir%/../uploads/chunks"
