version: "3"

services:
  app:
    ports:
      - "10060:80"

  db:
    ports:
       - "10061:3306"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
          - db
      ports:
          - "10062:80"
      environment:
          MYSQL_ROOT_PASSWORD: root
          PMA_HOST: db
