public:
  resource: ../../src/Controller/Open
  type: annotation
  prefix: /public

admin:
    resource: ../../src/Controller/Admin
    type: annotation
    prefix: /admin

user:
    resource: ../../src/Controller/User
    type: annotation
    prefix: /

security:
    resource: ../../src/Controller/Security
    type: annotation
    prefix: /
